# Generated by Django 2.1.2 on 2018-10-08 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectId', models.IntegerField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('documentId', models.IntegerField(max_length=50)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
