# Generated by Django 2.1.2 on 2018-10-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='documentId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='document',
            name='projectId',
            field=models.IntegerField(),
        ),
    ]
