# Generated by Django 2.1.2 on 2018-10-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20181008_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cid', models.IntegerField()),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
